name: expense_tracker

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.66.0
  flutter_bloc: ^8.1.2
  font_awesome_flutter: ^10.7.0

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
